sudo: required
services:
  - docker

before_install:
  - docker build -t lfbos19/docker-react -f Dockerfile.dev .

script:
  - docker run --env CI=test lfbos19/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "$AWS_REGION"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "$AWS_BUCKET_NAME"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"